#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m rule --add app="^(微信)" manage=off sub-layer=normal
yabai -m config external_bar               all:40:0       \
                mouse_follows_focus        off            \
                focus_follows_mouse        off            \
                window_zoom_persist        off            \
                window_placement           second_child   \
                window_shadow              float          \
                window_opacity             off             \
                window_opacity_duration    0.2            \
                active_window_opacity      1.0            \
                normal_window_opacity      0.9            \
                window_animation_duration  0.5            \
                window_animation_easing    ease_out_quint \
                insert_feedback_color      0xff9dd274     \
                split_ratio                0.50           \
                auto_balance               off            \
                mouse_modifier             fn             \
                mouse_action1              move           \
                mouse_action2              resize         \
                mouse_drop_action          swap           \
                                                          \
                top_padding                12              \
                bottom_padding             12              \
                left_padding               14             \
                right_padding              14             \
                window_gap                 10

# Exclude problematic apps from being managed:
yabai -m rule --add app="^(LuLu|Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|App Store|Steam|Alfred|Activity Monitor)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Select file to save to" app="^Inkscape$" title="Select file to save to" manage=off

yabai -m config layout bsp
# 浮动窗口
yabai -m rule --add app="^(System Settings|系统设置)" manage=off sub-layer=normal
yabai -m rule --add app="^(CleanMyMac)" manage=off sub-layer=normal
yabai -m rule --add app="^(Clash Verge)" manage=off sub-layer=normal
yabai -m rule --add app="^(QQ)" manage=off sub-layer=normal
yabai -m rule --add app="^(微信)" manage=off sub-layer=normal
yabai -m rule --add app="^(飞书)" manage=off sub-layer=normal
yabai -m rule --add app="^(访达)" manage=off sub-layer=normal
otherApp='^(腾讯会议|Bob|IINA|Raycast|Tencent Lemon|Clash Verge|360安全云盘|arknights|音乐|MotionPro| discover |ChatGPT|PlayCover|访达|Calendar|日历|地图|System Preferences|朋友圈|小程序|Downie 4|Shadowrocket| |照片|Epson iProjection|系统设置|1Password 7|Android Studio|印象笔记|MATLAB|CrossOver)$'

yabai -m rule --add app="${otherApp}" manage=off

# Space 2
yabai -m rule --add app="^Obsidian$" space=2

# Space 1
yabai -m rule --add app="^Google Chrome$" space=1

# Space 3
yabai -m rule --add app="^Cursor$" space=3
yabai -m rule --add app="^Visual Studio Code$" space=3

# Space 4
yabai -m rule --add app="^(WPS|WPS Office)$" space=4

# Space 5
yabai -m rule --add app="^QQ$" space=5
yabai -m rule --add app="^(微信|WeChat)$" space=5

# Space 6
yabai -m rule --add app="^Clash Verge$" space=6
yabai -m rule --add app="^Spotify$" space=6

echo "yabai configuration loaded.."
