require("items.widgets.battery")
require("items.widgets.volume")
require("items.widgets.cpu_temp")
require("items.widgets.cpu")
require("items.widgets.memory")
require("items.widgets.gpu")
require("items.widgets.wifi")
require("items.widgets.wechat_and_qq")
require("items.widgets.ai_usage")
-- Focus: pomodoro + todos (order matters for right-side layout)
require("items.widgets.pomodoro")
require("items.widgets.obsidian_todos")
require("items.widgets.focus_bracket")