
eval "$(/opt/homebrew/bin/brew shellenv)"

# Added by Obsidian
export PATH="$PATH:/Applications/Obsidian.app/Contents/MacOS"


# Added by Antigravity CLI installer
export PATH="/Users/xianull/.local/bin:$PATH"
